---
- hosts: webservers
  become: True
  tasks:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start the container
      docker_container:
        name: webapp
        image: "the1amit/webapp"
        state: started
        ports:
          - "8070:5000"
          - "http://vmpl1000.eastus.cloudapp.azure.com:8071:5001"
