---
- hosts: webservers
  become: True
  tasks:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start the container
      docker_container:
        name: webapp
        image: "the1amit/webapp"
        state: started
        ports:
          - "8080:8080"
        expose:
          - "8085"
