---
- hosts: webservers
  become: True
  tasks:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start the container
      docker_container:
        name: webapp
        image: "the1amit/webapp"
        state: started
        ports:
          - "2000:8000"
          - "http://vmpl1000.eastus.cloudapp.azure.com:2001:8001"
